spring:
  data:
    mongodb:
#      uri: mongodb://172.21.212.168/MapArchive
      uri: mongodb://127.0.0.1/MapArchive
#      uri: mongodb://172.21.213.33/MapArchiveDB


#resourcePath: /home/MapArchive/mapArchiveFiles
resourcePath: E:/mapArchiveFiles

logging:
  config: classpath:logging-config.xml

#logback:
#  LOG_HOME: /home/MapArchive/logs
logback:
  LOG_HOME: E:/mapArchiveFiles/logs
