#swagger:
#  enable: true

spring:
  data:
    mongodb:
#      uri: mongodb://127.0.0.1/MapArchive
      uri: mongodb://localhost/MapArchiveDB

#  datasource:
#    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite:E:/mapArchiveFiles/demo.mbtiles

resourcePath: E:/mapArchiveFiles
#dataServerPath: Z:/
#resourcePath: Z:/mapArchiveFiles

#logging:
#  config: classpath:logging-config.xml

#logback:
#  LOG_HOME: E:/mapArchiveFiles/logs


#ipAndPort: "http://127.0.0.1:8999"